spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      # 配置策略
      matching-strategy: ant-path-matcher
---
#开发环境
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/haidilou?useSSL=false&useServerPrepStmts=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 8609*AABV
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 80
---
#生产环境
spring:
  config:
    activate:
      on-profile: pro
server:
  port: 81
---
#测试环境
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/haidilou?useSSL=false&useServerPrepStmts=true&serverTimezone=Asia/Shanghai
    username: root
    password: Sun20011119
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 82